### ISSUE TITLE
compiling error digitalTapeRecorder.ino

### ISSUE THREAD

**Issue by MarkusPlehn** [mrWheel/KIM_TapeDevice#2]
i have problems to compile the digitalTapeRecorder.ino. I have installed all needed libraries but it end´s with error:

**

> H:\KIM-1\KIM_TapeDevice-master\digitalTapeRecorder\networkStuff.h:122:15: error: 'using ESP8266HTTPUpdateServer = class esp8266httpupdateserver::ESP8266HTTPUpdateServerTemplate<WiFiServer>' {aka 'class esp8266httpupdateserver::ESP8266HTTPUpdateServerTemplate<WiFiServer>'} has no member named 'setIndexPage'
>   122 |   httpUpdater.setIndexPage(UpdateServerIndex);
>       |               ^~~~~~~~~~~~
> H:\KIM-1\KIM_TapeDevice-master\digitalTapeRecorder\networkStuff.h:123:15: error: 'using ESP8266HTTPUpdateServer = class esp8266httpupdateserver::ESP8266HTTPUpdateServerTemplate<WiFiServer>' {aka 'class esp8266httpupdateserver::ESP8266HTTPUpdateServerTemplate<WiFiServer>'} has no member named 'setSuccessPage'
>   123 |   httpUpdater.setSuccessPage(UpdateServerSuccess);
> > cc1plus.exe: some warnings being treated as errors
> 
> exit status 1
> 
> Compilation error: 'using ESP8266HTTPUpdateServer = class esp8266httpupdateserver::ESP8266HTTPUpdateServerTemplate<WiFiServer>' {aka 'class esp8266httpupdateserver::ESP8266HTTPUpdateServerTemplate<WiFiServer>'} has no member named 'setIndexPage'**
> 

what is going wrong ?

(Arduino IDE 2.3.3, Windows 10 X64)

**Comment by mrWheel** [comment]
Not sure what is going wrong but please use the ArduinoIDE version that I have used (1.8.x) and try again. 

Met vriendelijke groet, With kind regards, Mit freundlichen Grüßen, 此致，敬礼.
Willem

----------
Een klein toetsenbord en grote vingers maken de kans op vertikkingen groot. Excuses daarvoor. 
Verstuurd vanaf mijn mobiele telefoon. 


Op 12 nov 2024 om 16:44 heeft Markus64 ***@***.***> het volgende geschreven:

﻿


i have problems to compile the digitalTapeRecorder.ino. I have installed all needed libraries but it end´s with error:

**
H:\KIM-1\KIM_TapeDevice-master\digitalTapeRecorder\networkStuff.h:122:15: error: 'using ESP8266HTTPUpdateServer = class esp8266httpupdateserver::ESP8266HTTPUpdateServerTemplate' {aka 'class esp8266httpupdateserver::ESP8266HTTPUpdateServerTemplate'} has no member named 'setIndexPage'
122 | httpUpdater.setIndexPage(UpdateServerIndex);
| ^~~~~~~~~~~~
H:\KIM-1\KIM_TapeDevice-master\digitalTapeRecorder\networkStuff.h:123:15: error: 'using ESP8266HTTPUpdateServer = class esp8266httpupdateserver::ESP8266HTTPUpdateServerTemplate' {aka 'class esp8266httpupdateserver::ESP8266HTTPUpdateServerTemplate'} has no member named 'setSuccessPage'
123 | httpUpdater.setSuccessPage(UpdateServerSuccess);

cc1plus.exe: some warnings being treated as errors

exit status 1

Compilation error: 'using ESP8266HTTPUpdateServer = class esp8266httpupdateserver::ESP8266HTTPUpdateServerTemplate' {aka 'class esp8266httpupdateserver::ESP8266HTTPUpdateServerTemplate'} has no member named 'setIndexPage'**

what is going wrong ?

(Arduino IDE 2.3.3, Windows 10 X64)

**Comment by MarkusPlehn** [comment]
OK, i installed Arduino IDE 1.8.18 and now i get this:

> H:\KIM-1\KIM_TapeDevice-master\digitalTapeRecorder\digitalTapeRecorder.ino: In function 'char read1Nibble(fs::File)':
digitalTapeRecorder:257:1: error: control reaches end of non-void function [-Werror=return-type]
  257 | } // read1Nibble()
      | ^
cc1plus.exe: some warnings being treated as errors
exit status 1
control reaches end of non-void function [-Werror=return-type]

**Comment by MarkusPlehn** [comment]
`char read1Nibble(File fIn)
{
  while (true && fIn.available())
  {
    char nibbleIn = fIn.read();    // skip ID lnibble
    if (isHex((char)nibbleIn))
    {
       return nibbleIn;
    }
    
  } 
  _**return 0;**_
  
} // read1Nibble()
`
seems to fix the problem

**Comment by mrWheel** [comment]
Well .. that is absolutely an error.
The function should always return ‘something’!
If ‘0’ zero is the preferred value I don’t know, but if it works use it.
Please let me know if the system works!

**Comment by MarkusPlehn** [comment]
yes ok. compiling works, but flashing won´t work. I use this FTDI with FT232RL Chip without RESET Line.
I soldered a wire from Chip RESET and connect it to RTS at the TapeRecorderBoard. Is this correct ? All other wire´s plugged in like silkscreen. But the Reset kills the USB connection . 

so i think i missunderstand and i am a little bit confused what to do with:

> You do need a FTDI board with a RESET and DTR pin. Many FTDI boards have DTR and CTS on the header but you cannot flash the digital Tape Recorder with such a board. Most FTDI board make use of a CH340 chip (or something like that) that do have a RESET pin. It's easy to wire this pin to the CTS pin on the outside (interrupt the CTS track before you solder the RESET line).

**Comment by mrWheel** [comment]
You need to connect the [reset] from the FTDI to the [reset] on the FDTI header on the dTR.

From another post:

> Fortunately, I still had a few USB-to-Serial boards with a CH340G chip on board. I use the CH340 chip in several of my other designs as well, so I’m familiar with its capabilities. This board provides not only GND, Tx, and Rx, but also brings CTS to the outside. What’s still missing is a connection for RST. I soldered this directly to the chip and placed all connections in a 6-pin Pololu housing. With this board, flashing works flawlessly!

Make sure your FTDI is 3v3!
![](https://willem.aandewiel.nl/wp-content/uploads/2022/12/FTDI-Mod1-1.png)

![](https://willem.aandewiel.nl/wp-content/uploads/2022/12/FTDI_Casing-C.png)

An alternative that works out-of-the-box:
https://www.amazon.nl/dp/B075GH9H3P?_encoding=UTF8&psc=1&ref=cm_sw_r_ud_dp_CQABTW1MFGX3HBMQ3GB6&ref_=cm_sw_r_ud_dp_CQABTW1MFGX3HBMQ3GB6&social_share=cm_sw_r_ud_dp_CQABTW1MFGX3HBMQ3GB6&skipTwisterOG=1


![](https://m.media-amazon.com/images/I/71lUhcoKgJL._SX522_.jpg)

**Comment by MarkusPlehn** [comment]
![IMG_20241113_114558~2](https://github.com/user-attachments/assets/371995e2-5471-4bd2-a3a4-ff76148032b0)
this was my first idea yesterday and it doesn't work . Then I trying the RESET line, no success.

But new day: successful flashing 😃🙄🤔
without RESET from FTDI board.

thanks for your help 🙋😁

**Comment by mrWheel** [comment]
Ok! 
That is great news!
Glad it finally works!
